version: "3.3"

services:

  # LDAP-related

  ldap:
    image: osixia/openldap:1.3.0
    restart: always
    env_file:
      - .env
    volumes:
        - ldap_data:/var/lib/ldap
        - ldap_slapd:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    restart: always
    ports:
        - 8081:443
    environment: 
        PHPLDAPADMIN_LDAP_HOSTS: ldap
    depends_on: 
      - ldap


  # Database-related

  database:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 8082:8080
    depends_on: 
      - database


  # Service-related

  api:
    build: ./api
    image: flavienb/reactjs-flask-ldap-boilerplate-api:develop
    restart: always
    volumes:
      - ./api/app:/app
      - ./logs/api:/logs
      - api_migrations:/migrations
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      FLASK_LEVEL: "dev" # dev, test or prod
      LOG_LEVEL: "DEBUG" # DEBUG, INFO, WARNING or ERROR
    depends_on:
      - ldap
      - database

  app:
    build: ./app
    image: flavienb/reactjs-flask-ldap-boilerplate-app:develop
    restart: always
    volumes:
      - ./app/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"

  # We set-up an NGINX to have a unique endpoint for app & api
  nginx:
    build: ./nginx
    image: flavienb/reactjs-flask-ldap-boilerplate-nginx:develop
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
      - app

volumes:
  database:
  ldap_data:
  ldap_slapd:
  api_migrations:
