apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: my-app
  name: ldap-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: scw-bssd-retain # Specific to Scaleway Kapsule
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: my-app
  name: ldap-slapd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: scw-bssd-retain # Specific to Scaleway Kapsule
  resources:
    requests:
      storage: 3Gi